description: LSST Telescope Parameters
instrument: lsst.obs.lsst.LsstCam

tasks:
  estimateZernikesScienceSensorTask:
    class: lsst.ts.wep.task.EstimateZernikesScienceSensorTask.EstimateZernikesScienceSensorTask
    config:
      instObscuration: 0.61
      instFocalLength: 10.312
      instApertureDiameter: 8.36
      instDefocalOffset: 1.5e-3
      instPixelSize: 10.0e-6