black: false
clang-format: false
flake8: false
format-xmllint: true
<<<<<<< HEAD
isort: false
=======
isort: true
>>>>>>> 6962d285 (All Peter's work)
mypy: true
check-yaml: true
check-xml: true
ruff: true
