---

# Default setting

# 1 pixel = 0.2 arcsec
pixelToArcsec: 0.2

# Bright star catalog (BSC) database ("localDb" or "file")
# localDb: Use the local database (not support yet)
# file: Use the sky file
bscDb: file

# Camera MJD
cameraMJD: 59580.0

# Star (donut) radious in pixel
# Donut radius is 63 pixel if the defocal distance is 1.5 mm
starRadiusInPixel: 63

# Spacing coefficient
spacingCoef: 2.5

# Max number of neighboring star
maxNumOfNbrStar: 0

# Distance to be vignette
distVignette: 1.75

# Algorithm to solve the Poisson's equation in the transport of intensity
# equation (TIE). It can be "fft" or "exp".
poissonSolver: exp

# Optical model. It can be "paraxial", "onAxis", or "offAxis"
opticalModel: offAxis

# Defocal distance in mm (default is 1.5 mm)
dofocalDistInMm: 1.5

# Donut image size in pixel (default value at 1.5 mm)
donutImgSizeInPixel: 160

# Camera mapper for the data butler to use
camMapper: phosim
