description: LSST Telescope Parameters
instrument: lsst.obs.lsst.Latiss

tasks:
  estimateZernikesLatissTask:
    class: lsst.ts.wep.task.EstimateZernikesLatissTask.EstimateZernikesLatissTask
    config:
      instObscuration: 0.3525
      instFocalLength: 21.6
      instApertureDiameter: 1.2
      instDefocalOffset: 3.28e-2
      instPixelSize: 10.0e-6